version: '2'
services:
  walle-db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    container_name: walle-db
    command: [
       "--log-bin=mysql-bin",
       "--server-id=1",
       "--character-set-server=utf8",
       "--collation-server=utf8_general_ci",
       "--innodb_flush_log_at_trx_commit=1",
       "--sync_binlog=1"
       ]
    environment:
      MYSQL_ROOT_PASSWORD: 12wsxCDE#
      MYSQL_DATABASE: walle
      MYSQL_USER: prodba
      MYSQL_PASSWORD: 12wsxCDE#
    ports:
      - 3306:3306
    networks:
      default:
        ipv4_address: 172.168.96.223
    extra_hosts:
      - "dns:172.168.96.2"
      - "openldap:172.168.96.3"

  walle:
    image: walle
    restart: always
    container_name: walle
    ports:
      - 80:80
    networks:
      default:
        ipv4_address: 172.168.96.222
    depends_on:
      - walle-db
    volumes:
      - ./app_data:/data/www/deploy
      - ./key_ssh:/home/ops/.ssh
    extra_hosts:
      - "openldap:192.168.1.11"

networks:
  sys_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.168.96.0/24
          gateway: 172.168.96.1

